# pip install mkdocs mkdocs-material
# mkdocs serve
# mkdocs gh-deploy

site_name: Vaultaire
repo_name: Vaultaire
repo_url: https://github.com/manosbatsis/vaultaire
site_description: "Query DSL and data access utilities for Corda developers."
site_author: Manos Batsis
remote_branch: gh-pages
google_analytics: ['UA-131279953-1', 'manosbatsis.github.io']
copyright: 'Copyright &copy; 2019 Manos Batsis'

theme:
  name: 'material'
#  logo: 'images/icon-square.png'
#  favicon: 'images/icon-square.png'
  palette:
    primary: 'cyan'
    accent: 'deep-purple'

#extra_css:
#  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - tables
  - admonition

nav:
  - 'Overview': index.md
  - 'Query DSL': query-dsl.md
  - 'State Services': state-servicse.md
  - 'API': /vaultaire/0.x/index.html
  - 'FAQ': faq.md
#  - 'Stack Overflow ⏏': https://stackoverflow.com/questions/tagged/kotlinpoet?sort=active
  - 'Change Log': changelog.md
  - 'Credits': credits.md
