// -------------------- DO NOT EDIT -------------------
//  This file is automatically generated by Vaultaire,
//  see https://manosbatsis.github.io/vaultaire
// ----------------------------------------------------
package com.github.manosbatsis.vaultaire.plugin.accounts.dto

import com.github.manotbatsis.kotlin.utils.api.Dto
import com.github.manotbatsis.kotlin.utils.api.DtoInsufficientMappingException
import com.r3.corda.lib.accounts.contracts.states.AccountInfo
import net.corda.core.contracts.UniqueIdentifier
import net.corda.core.identity.Party
import net.corda.core.serialization.CordaSerializable

/**
 * A [AccountInfo]-specific [Dto] implementation
 */
@CordaSerializable
data class AccountInfoDto(
  var name: String? = null,
  var host: Party? = null,
  var identifier: UniqueIdentifier? = null
) : Dto<AccountInfo> {
  /**
   * Create a patched copy of the given [AccountInfo] instance,
   * updated using this DTO's non-null properties.
   */
  override fun toPatched(original: AccountInfo): AccountInfo {
    val patched = AccountInfo(
          name = this.name ?: original.name,
          host = this.host ?: original.host,
          identifier = this.identifier ?: original.identifier
    )
    return patched
  }

  /**
   * Create an instance of [AccountInfo], using this DTO's properties.
   * May throw a [DtoInsufficientStateMappingException] 
   * if there is mot enough information to do so.
   */
  override fun toTargetType(): AccountInfo {
    try {
       return AccountInfo(
          name = this.name!!,
          host = this.host!!,
          identifier = this.identifier!!
       )
    }
    catch(e: Exception) {
       throw DtoInsufficientMappingException(exception = e)
    }
  }

  companion object {
    /**
     * Create a new DTO instance using the given [AccountInfo] as source.
     */
    fun mapToDto(original: AccountInfo): AccountInfoDto =
        com.github.manosbatsis.vaultaire.plugin.accounts.dto.AccountInfoDto(
          name = original.name,
          host = original.host,
          identifier = original.identifier
    )

  }
}
