// -------------------- DO NOT EDIT -------------------
//  This file is automatically generated by Vaultaire,
//  see https://manosbatsis.github.io/vaultaire
// ----------------------------------------------------
package com.github.manosbatsis.vaultaire.plugin.accounts.dto

import com.github.manosbatsis.vaultaire.dto.VaultaireDto
import com.r3.corda.lib.accounts.contracts.states.AccountInfo
import net.corda.core.contracts.UniqueIdentifier
import net.corda.core.identity.Party
import net.corda.core.serialization.CordaSerializable

/**
 * A [AccountInfo]-specific [VaultaireDto] implementation
 */
@CordaSerializable
data class AccountInfoStateDto(
  var name: String? = null,
  var host: Party? = null,
  var identifier: UniqueIdentifier? = null
) : VaultaireDto<AccountInfo> {
  /**
   * Create a patched copy of the given [AccountInfo] instance,
   * updated using this DTO's non-null properties.
   */
  override fun toPatched(original: AccountInfo): AccountInfo {
    val patched = AccountInfo(
          name = this.name ?: original.name,
          host = this.host ?: original.host,
          identifier = this.identifier ?: original.identifier
    )
    return patched
  }

  /**
   * Create an instance of [AccountInfo], using this DTO's properties.
   * May throw a [DtoInsufficientStateMappingException] 
   * if there is mot enough information to do so.
   */
  override fun toTargetType(): AccountInfo {
       return AccountInfo(
          name = this.name?:errNull("name"),
          host = this.host?:errNull("host"),
          identifier = this.identifier?:errNull("identifier")
       )
  }

  companion object {
    /**
     * Create a new DTO instance using the given [AccountInfo] as source.
     */
    fun mapToDto(original: AccountInfo): AccountInfoStateDto =
        com.github.manosbatsis.vaultaire.plugin.accounts.dto.AccountInfoStateDto(
          name = original.name,
          host = original.host,
          identifier = original.identifier
    )

  }
}
